version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.data/html:/usr/share/nginx/html
      - ./.data/dhparam:/etc/nginx/dhparam
      - ./.data/vhost:/etc/nginx/vhost.d
      - ./.data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets-encrypt
    depends_on:
      - "nginx-proxy"
    volumes:
      - ./.data/certs:/etc/nginx/certs:rw
      - ./.data/vhost:/etc/nginx/vhost.d
      - ./.data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: io.cristallum.grid
